import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import styles from './page.module.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Library App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" />
      </head>
      <body className={inter.container}>
        <nav className={styles.navMenu}>
          <Image src="/img/logo.png" alt="" width={180} height={137} />
          <h2 className="pageTitle">CMPS-312 Library</h2>
        </nav>
        <hr></hr>
        {children}
      </body>
    </html >
  )
}
